Repository neo4j/docs-java-reference, pull requests merged in 2022-01, with the labels that each got.

#6 Fix typo
  modules/ROOT/pages/extending-neo4j/index.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 3.5, cherry-pick this forward

#13 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: 4.0, cherry-pick this forward

#15 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: 4.2, cherry-picked

#14 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: 4.1, cherry-picked

#17 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: 4.4, cherry-picked

#16 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: 4.3, cherry-picked

#18 Fixed broken link to 3.5 traversal framework
  modules/ROOT/pages/traversal-framework.adoc
Labels: cherry-picked, 5.0
