Repository neo4j/docs-java-reference, pull requests merged in 2022-09, with the labels that each got.

#57 4.4-xrefs-to-links
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/indexes.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/traversal-framework/bidirectional-traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
  preview.yml
  publish.yml
Labels: 4.4, clean-build

#55 4.2-xrefs-to-links
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/indexes.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/traversal-framework/bidirectional-traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
  preview.yml
Labels: 4.2, clean-build

#54 4.1-xrefs-to-links
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/indexes.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/traversal-framework/bidirectional-traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
  preview.yml
Labels: 4.1, clean-build

#53 4.0-xrefs-to-links
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/indexes.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/traversal-framework/bidirectional-traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
  preview.yml
Labels: 4.0, clean-build

#52 Replace external xrefs with links
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/indexing.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/explicit-indexes.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/traversal-framework.adoc
  package-lock.json
  package.json
  preview.yml
Labels: 3.5, clean-build

#58 Fix typo in attribute declaration
  modules/ROOT/pages/jmx-metrics.adoc
  preview.yml
Labels: 3.5, clean-build

#59 Update dependency versions
  package-lock.json
  package.json
Labels: 4.4

#61 Fixing broken links
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: 4.4, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick this forward, cherry-pick-this-to-4.3, cherry-pick-this-to-4.0

#63 5.0 Cherry-pick of 61
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: cherry-picked, 5.0

#64 4.3 Cherry-pick of #61
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: 4.3, cherry-picked

#65 4.2 Cherry-pick of #61
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: 4.2

#66 4.1 Chery-pick of (#61)
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: 4.1, cherry-picked

#67 Cherry-pick of #61
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: 4.0, cherry-picked

#68 5.1 Cherry-pick of (#61)
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
Labels: cherry-picked

#62 Fix two traversal links
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/traversal-framework-example.adoc
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, 5.0, cherry-pick-this-to-4.4, cherry-pick-this-to-4.3, clean-build, cherry-pick-this-to-4.0
