Repository neo4j/docs-java-reference, pull requests merged in 2022-08, with the labels that each got.

#39 Undeprecate the Traversal API and bring back old examples
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 5.0

#40 Fix up misses in Traversal API documentation
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 5.0

#41 4.4 Undeprecate Traversal API
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.4, cherry-picked

#42 4.3 Undeprecate Traversal API
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.3, cherry-picked

#43 4.2 Undeprecate Traversal API
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.2, cherry-picked

#44 4.1 Undeprecate Traversal API
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.1, cherry-picked

#45 4.0 Undeprecate Traversal API
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/bidirectional-example.png
  modules/ROOT/images/traversal_framework_example.svg
  modules/ROOT/images/traversal_order_example_graph.png
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.0, cherry-picked

#46 Editorial review of the undeprecated traversal framework for 5.0
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 5.0

#47 Editorial review of the undeprecated traversal framework for 5.0 (#46)
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.4, cherry-picked

#51 Editorial review of the undeprecated traversal framework for 5.0 (#46)
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.3, cherry-picked

#48 Editorial review of the undeprecated traversal framework for 5.0 (#46)
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.2, cherry-picked

#49 Editorial review of the undeprecated traversal framework for 5.0 (#46)
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.1, cherry-picked

#50 Editorial review of the undeprecated traversal framework for 5.0 (#46)
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: documentation, 4.0, cherry-picked
