Repository neo4j/docs-java-reference, pull requests merged in 2022-12, with the labels that each got.

#72 Fixing broken link
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
Labels: documentation, 5.0

#75 Fix the broken links
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: 5.0, cherry-pick-this-to-4.4, cherry-pick-this-to-4.3

#76 4.4 broken link
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: 4.4, cherry-picked

#78 4.3 broken link
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: 4.3, cherry-picked

#77 Fixed the broken links
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: cherry-picked, 5.x

#73 Correct heading level
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: dev, cherry-pick-this-to-5.x

#79 Correct heading level
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: cherry-picked, 5.x
