Repository neo4j/docs-java-reference, pull requests merged in 2022-05, with the labels that each got.

#35 professional contact added link
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.4, cherry-pick this forward, cherry-pick-this-to-4.3

#36 resolved conflicts
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.3, cherry-picked

#38 5.0 cherry pick 35
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-picked, 5.0
