Repository neo4j/docs-java-reference, pull requests merged in 2023-04, with the labels that each got.

#117 Fixing link to github
  modules/ROOT/pages/java-embedded/terminate.adoc
Labels: cherry-pick this forward, 5.x

#119 Clarify documentation around lost Cypher updates
  modules/ROOT/pages/transaction-management.adoc
Labels: 5.x, cherry-pick-this-to-5.x

#120 Update the version to 5.8
  antora.yml
Labels: dev, do not cherry-pick

#121 Update the version to 5.7
  antora.yml
Labels: bug, 5.x
