Repository neo4j/docs-java-reference, pull requests merged in 2023-06, with the labels that each got.

#125 Fixing broken link to new section in the Cypher manual
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: dev, cherry-pick-this-to-4.0

#126 Fixing broken link to new section in the Cypher manual (#125)
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: cherry-picked, 5.x

#127 Fixing broken link to new section in the Cypher manual #125
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: 4.4, cherry-picked

#128 Fixing broken link to new section in the Cypher manual #125
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: 4.3, cherry-picked

#129 Fixing broken link to new section in the Cypher manual #125
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: 4.2, cherry-picked

#130 Fixing broken link to new section in the Cypher manual #125
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: 4.1, cherry-picked

#131 Fixing broken link to new section in the Cypher manual #125
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
Labels: 4.0, cherry-picked

#133 Update version to 5.10
  antora.yml
Labels: 5.10

#132 Reword the content left on the Transaction mgmt page after moving parts of it to the operations manual
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/unique-nodes.adoc
  modules/ROOT/pages/transaction-management.adoc
Labels: 5.x, cherry-pick-this-to-5.x, kernel

#134 Reword the content left on the Transaction mgmt page after moving parts of it to the operations manual
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/unique-nodes.adoc
  modules/ROOT/pages/transaction-management.adoc
Labels: cherry-picked, 5.x

#135 Removing setting that is no longer available after 5.x
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: dev, cherry-pick-this-to-5.x, kernel

#136 Removing setting that is no longer available after 5.x (#135)
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-picked, 5.x

#137 fix a broken link
  modules/ROOT/pages/transaction-management.adoc
Labels: cherry-pick-this-to-5.x

#138 fix a broken link (#137)
  modules/ROOT/pages/transaction-management.adoc
Labels: cherry-picked, 5.x
