Repository neo4j/docs-java-reference, pull requests merged in 2023-12, with the labels that each got.

#169 Adding specifications to Windows configuration (#168)
  modules/ROOT/pages/jmx-metrics.adoc
Labels: cherry-picked, 5.x

#170 Adding specifications to Windows configuration (#168)
  modules/ROOT/pages/jmx-metrics.adoc
Labels: 4.4, cherry-picked

#173 bump to version 5.15
  antora.yml
Labels: 5.15

#181 update version to 4.4.29
  antora.yml
Labels: 4.4
