Repository neo4j/docs-java-reference, pull requests merged in 2023-05, with the labels that each got.

#123 update version in dev to 5.9
  antora.yml
Labels: dev, do not cherry-pick

#122 5.x update version to 5.8
  antora.yml
  modules/ROOT/pages/transaction-management.adoc
Labels: do not cherry-pick, 5.8

#124 Add NODES 23 ad
  publish.yml
Labels: 5.x
