Repository neo4j/docs-java-reference, pull requests merged in 2023-02, with the labels that each got.

#96 Add a note about jmx remote connections
  modules/ROOT/pages/jmx-metrics.adoc
Labels: dev, cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#100 Add a note about jmx remote connections (#96)
  modules/ROOT/pages/jmx-metrics.adoc
Labels: 4.4, cherry-picked

#98 Update the documentation for procedures and functions
  modules/ROOT/pages/extending-neo4j/functions.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: documentation, 4.4

#99 Add a note about jmx remote connections (#96)
  modules/ROOT/pages/jmx-metrics.adoc
Labels: cherry-picked, 5.x

#97 Update the documentation for procedures and functions
  modules/ROOT/pages/extending-neo4j/functions.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: documentation, dev, 5.x, cherry-pick-this-to-5.x

#101 Update the documentation for procedures and functions to have up to date code examples from linked github repo. (#97)
  modules/ROOT/pages/extending-neo4j/functions.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: cherry-picked, 5.x

#102 added section about custom seed providers
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: documentation, cherry-pick this forward, dev, 5.x

#103 Adding information about the version of junit used in the example
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.4, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick this forward, cherry-pick-this-to-4.3, cherry-pick-this-to-4.0, cherry-pick-this-to-5.x

#106 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: cherry-picked, 5.x

#107 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: cherry-picked, 5.x

#108 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.3, cherry-picked

#109 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.2, cherry-picked

#110 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.1, cherry-picked

#111 Adding information about the version of junit used in the example (#103)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.0, cherry-picked

#112 resolved conflict
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: cherry-picked, 5.x

#113 Update Neo4j version
  antora.yml
Labels: 5.6
