Repository neo4j/docs-java-reference, pull requests merged in 2023-11, with the labels that each got.

#155 add a link to the Browser Manual
  modules/ROOT/pages/java-embedded/hello-world.adoc
Labels: cherry-pick-this-to-5.x

#157 add a link to the Browser Manual (#155)
  modules/ROOT/pages/java-embedded/hello-world.adoc
Labels: 4.4, cherry-picked

#156 add a link to the Browser Manual (#155)
  modules/ROOT/pages/java-embedded/hello-world.adoc
Labels: cherry-picked, 5.x

#158 Disclaimer note about Java driver and reference
  modules/ROOT/pages/index.adoc
Labels: dev, cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#160 Disclaimer note about Java driver and reference (#158)
  modules/ROOT/pages/index.adoc
Labels: 4.4, cherry-picked

#159 Disclaimer note about Java driver and reference (#158)
  modules/ROOT/pages/index.adoc
Labels: cherry-picked, 5.x

#162 Update Java embdedded docs to remove ClusterDatabaseManagementService…
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-picked, 5.x

#164 bump exact version to 4.4.28
  antora.yml
Labels: 4.4, do not cherry-pick

#165 update version to 5.14 (#153)
  antora.yml
Labels: 5.14

#166 add connections ad
  antora.yml
Labels: 5.14

#167 bump dev version to 5.15
  antora.yml
Labels: 5.15
