Repository neo4j/docs-java-reference, pull requests merged in 2023-01, with the labels that each got.

#80 Editorial review of the Java Reference Guide
  README.adoc
  modules/ROOT/pages/extending-neo4j/aggregation-functions.adoc
  modules/ROOT/pages/extending-neo4j/best-practices.adoc
  modules/ROOT/pages/extending-neo4j/customized-code.adoc
  modules/ROOT/pages/extending-neo4j/full-text-analyzer-provider.adoc
  modules/ROOT/pages/extending-neo4j/functions.adoc
  modules/ROOT/pages/extending-neo4j/index.adoc
  modules/ROOT/pages/extending-neo4j/procedures.adoc
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
  modules/ROOT/pages/extending-neo4j/security-plugins.adoc
  modules/ROOT/pages/extending-neo4j/server-debugging.adoc
  modules/ROOT/pages/extending-neo4j/unmanaged-extensions.adoc
  modules/ROOT/pages/extending-neo4j/values-and-types.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/java-embedded/bolt.adoc
  modules/ROOT/pages/java-embedded/cypher-java.adoc
  modules/ROOT/pages/java-embedded/entities.adoc
  modules/ROOT/pages/java-embedded/graph-algorithms.adoc
  modules/ROOT/pages/java-embedded/hello-world.adoc
  modules/ROOT/pages/java-embedded/index.adoc
  modules/ROOT/pages/java-embedded/indexes.adoc
  modules/ROOT/pages/java-embedded/logging.adoc
  modules/ROOT/pages/java-embedded/managing-resources.adoc
  modules/ROOT/pages/java-embedded/property-values.adoc
  modules/ROOT/pages/java-embedded/query-parameters.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
  modules/ROOT/pages/java-embedded/terminate.adoc
  modules/ROOT/pages/java-embedded/traversal.adoc
  modules/ROOT/pages/java-embedded/unique-nodes.adoc
  modules/ROOT/pages/jmx-metrics.adoc
  modules/ROOT/pages/transaction-management.adoc
  modules/ROOT/pages/traversal-framework/bidirectional_traversal_framework.adoc
  modules/ROOT/pages/traversal-framework/index.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_example.adoc
  modules/ROOT/pages/traversal-framework/traversal_framework_java_api.adoc
Labels: dev

#81 Adding information about system procedure annotation
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, dev, cherry-pick-this-to-4.4, cherry-pick-this-to-4.3, cherry-pick-this-to-4.0, cherry-pick-this-to-5.x

#82 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: cherry-picked, 5.x

#83 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.4, cherry-picked

#84 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.3, cherry-picked

#86 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.1, cherry-picked

#87 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.0, cherry-picked

#85 adding information about system procedure annotation (#81)
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: 4.2, cherry-picked

#88 Update Neo4j version
  antora.yml
Labels: 5.5

#89 Changing the order of topics as requested
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, dev, cherry-pick-this-to-4.4, cherry-pick-this-to-4.3, cherry-pick-this-to-4.0, cherry-pick-this-to-5.x

#90 changing the order of topics as requested (#89)
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-picked, 5.x

#91 Changing the order of topics as requested #89
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.4, cherry-picked

#92 Changing the order of topics as requested #89
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.3, cherry-picked

#95 Changing the order of topics as requested #89
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.0, cherry-picked

#94 Changing the order of topics as requested #89
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: 4.1, cherry-picked
