Repository neo4j/docs-java-reference, pull requests merged in 2024-10, with the labels that each got.

#223 update the version to 4.4.38
  antora.yml
Labels: 4.4

#221 Add documentation for user procedure memory resource tracking
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: documentation, dev

#225 Add documentation for user procedure memory resource tracking
  modules/ROOT/pages/extending-neo4j/procedures.adoc
Labels: cherry-picked, 5.x

#227 Bump the Neo4j v.n. to 5.26 and the Java driver to 5.26.1
  antora.yml
Labels: 5.26
