Repository neo4j/docs-java-reference, pull requests merged in 2024-12, with the labels that each got.

#232 Remove `SeedProvider`
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: 2025.01

#240 Update antora.yml to include the LTS label
  antora.yml
Labels: 5.x, do not cherry-pick

#241 Update the version to 4.4.40
  antora.yml
Labels: 4.4
