Repository neo4j/docs-java-reference, pull requests merged in 2024-11, with the labels that each got.

#228 Fix the code example
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
Labels: cherry-pick-this-to-5.x

#229 Fix the code example (#228)
  modules/ROOT/pages/traversal-framework/traversal-framework-java-api.adoc
Labels: cherry-picked, 5.x

#222 Update setup.adoc
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-pick this forward, 5.x

#230 Update setup.adoc (#222)
  modules/ROOT/pages/java-embedded/setup.adoc
Labels: cherry-picked, dev

#231 Introduce `DatabaseSeedProvider`
  modules/ROOT/pages/extending-neo4j/project-setup.adoc
Labels: 5.26

#233 Update the version number
  antora.yml
Labels: 4.4, do not cherry-pick

#235 Update Java driver version
  antora.yml
Labels: 5.x
