Repository neo4j/docs-java-reference, pull requests merged in 2025-02, with the labels that each got.

#246 bump version to 4.4.41
  antora.yml
Labels: 4.4

#248 bump version to 2025.02
  antora.yml
Labels: 2025.02

#247 bump version to 5.26.2
  antora.yml
Labels: 5.x

#250 Update the neo4j-version-exact attribute in the antora.yml file
  antora.yml
Labels: THIS VERSION ONLY, 5.26

#251 Publish 2025.02
  antora.yml
  package.json
Labels: THIS VERSION ONLY

#252 Update dev version to 2025.03
  antora.yml
Labels: 2025.03

#253 Update version in antora.yml to 2025.02
  antora.yml
Labels: 2025.02

#254 Update version in antora.yml to 2025.03
  antora.yml
Labels: 2025.03

#255 use display_version to show 5.26
  antora.yml
Labels: 5.26

#256 Update workflows to 1.2.0
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
Labels: 5.x
